version: "3"
services:
    projeto-contab-01-pg:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USERNAME=${POSTGRES_USERNAME}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      volumes:
        - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: